# Generated by Django 3.2.2 on 2022-01-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(choices=[('로맨스', '로맨스'), ('판타지', '판타지'), ('스릴러', '스릴러'), ('코미디', '코미디'), ('SF', 'SF'), ('공포', '공포'), ('미스터리', '미스터리'), ('다큐', '다큐'), ('애니매이션', '애니매이션')], max_length=50, verbose_name='장르'),
        ),
    ]
